site_name: 'Deep Earthquake Catalog'
site_url: 'https://ai4eps.github.io/DeepEarthquakeCatalog'
site_description: 'Deep-learning-based Earthquake Catalogs'
site_author: 'Weiqiang Zhu'
docs_dir: docs/
repo_name: 'DeepEarthquakeCatalog'
repo_url: 'https://github.com/ai4eps/DeepEarthquakeCatalog'
nav:
  - Overview: README.md
  - Hawaii: 
    - Standard catalog: catalogs/Hawaii-220181101-20220501/standard.html
    - HypoDD catalog: catalogs/Hawaii-220181101-20220501/hypodd_cc.html
theme:
  name: 'material'
  features:
    - navigation.expand

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - redirects:
      redirect_maps:
        'deep-earthquake-catalog.md': 'https://ai4eps.github.io/DeepEarthquakeCatalog/'
        'deepearthquakecatalog.md': 'https://ai4eps.github.io/DeepEarthquakeCatalog/'
        'earthquakecatalog.md': 'https://ai4eps.github.io/DeepEarthquakeCatalog/'
        'catalog.md': 'https://ai4eps.github.io/DeepEarthquakeCatalog/'

# extra:
#   analytics:
#     provider: google
#     property: G-69DX3B35RK
